name: Pull locales

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  pull-locales:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
        name: Checkout docs
        with:
          path: docs
          token: ${{ secrets.BOTICORDAC_TOKEN }}
      - uses: actions/checkout@v3
        name: Checkout locales
        with:
          path: locales
          repository: boticord/localization
      - name: Generate some shit for Crowdin
        run: |
          cd docs
          npm ci
          npm run write-translations
          rm -rf ./locale/ru/docusaurus-plugin-content-docs/current
          cp -r docs ./locale/ru/docusaurus-plugin-content-docs/current
          cd ..
          cp -r ./docs/locale/ru/* ./locales
          
          git config --global user.email "bc@livixx.me"
          git config --global user.name "BoticordAC"
          git commit -a -m "chore: pull locales"
      - uses: ad-m/github-push-action@master
        name: Push changes
        with:
          github_token: ${{ secrets.BOTICORDAC_TOKEN }}
          branch: main
          repository: boticord/localization