name: Push locales to Crowdin

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  pull-locales:
    name: Pull locales
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
        name: Checkout docs
        with:
          path: docs
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        name: Checkout locales
        with:
          path: locales
          repository: boticord/localization
      - name: Specify the Git global safe directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Generate some shit for Crowdin
        run: |
          cd docs
          npm ci
          npm run write-translations
          rm -rf ./locale/ru/docusaurus-plugin-content-docs/current
          cp -r docs ./locale/ru/docusaurus-plugin-content-docs/current
          cd ..
          cp -r ./docs/locale/ru/* ./locales
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:boticord/localization.git
          BRANCH: main
          FOLDER: locales
          SSH_PRIVATE_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          MESSAGE: "chore: pull locales"
